# Binance USD-M Futures Classification Maps

This notebook shows how to get Binance official futures classification dictionaries from `exchangeInfo`:

- `underlyingType`: primary category, such as `COIN`, `EQUITY`, `PREMARKET`, `COMMODITY`, `INDEX`.
- `underlyingSubType`: official sector tags, such as `AI`, `Layer-1`, `Alpha`, `Pre-IPO`, `TradFi`.

The helper returns dictionaries where each key is a category/tag and each value is the sorted list of matching futures symbols.

## 1. Import Local Package

In [2]:
import sys
from pathlib import Path

import pandas as pd


def find_repo_path():
    candidates = [
        Path.cwd(),
        Path.cwd().parent,
        Path("/home/suncong/binance_klines_data_fetch"),
    ]
    for candidate in candidates:
        if (candidate / "binance_klines_data_fetch").is_dir():
            return candidate.resolve()
    raise RuntimeError("Could not find the binance_klines_data_fetch repo path")


repo_path = find_repo_path()
repo_path_str = str(repo_path)
if repo_path_str not in sys.path:
    sys.path.insert(0, repo_path_str)

from binance_klines_data_fetch import get_um_futures_classification_maps

print("Imported package from:", repo_path)

Imported package from: /home/suncong/binance_klines_data_fetch

## 2. Fetch Classification Maps

This cell calls Binance USD-M Futures `/fapi/v1/exchangeInfo`. By default, it includes `TRADING` contracts with `contractType` equal to `PERPETUAL` or `TRADIFI_PERPETUAL`, so it covers crypto perpetuals plus TradFi and Pre-IPO perpetuals.

In [3]:
classification_maps = get_um_futures_classification_maps(
    quote_assets=None,
    contract_types=("PERPETUAL", "TRADIFI_PERPETUAL"),
    unknown_label="UNKNOWN",
)

type_map = classification_maps["underlyingType"]
subtype_map = classification_maps["underlyingSubType"]

print("underlyingType groups:", len(type_map))
print("underlyingSubType groups:", len(subtype_map))

underlyingType groups: 5
underlyingSubType groups: 22

## 3. underlyingType: Primary Category To Symbols

In [4]:
type_summary = pd.DataFrame(
    [
        {
            "underlyingType": label,
            "symbol_count": len(symbols),
            "sample_symbols": symbols[:20],
        }
        for label, symbols in type_map.items()
    ]
).sort_values(["symbol_count", "underlyingType"], ascending=[False, True])

display(type_summary.reset_index(drop=True))

,underlyingType,symbol_count,sample_symbols
0,COIN,566,"[0GUSDT, 1000000BOBUSDT, 1000000MOGUSDT, 1000B..."
1,EQUITY,48,"[AAPLUSDT, AMDUSDT, AMZNUSDT, ARMUSDT, AVGOUSD..."
2,COMMODITY,8,"[BZUSDT, CLUSDT, COPPERUSDT, NATGASUSDT, XAGUS..."
3,PREMARKET,3,"[OPENAIUSDT, QNTXUSDT, SPCXUSDT]"
4,INDEX,2,"[ALLUSDT, BTCDOMUSDT]"

In [5]:
def symbols_frame(group_map, label):
    return pd.DataFrame({"symbol": group_map.get(label, [])})


for label in ["COIN", "EQUITY", "PREMARKET", "COMMODITY", "INDEX", "UNKNOWN"]:
    symbols = type_map.get(label, [])
    print(f"{label}: {len(symbols)} symbols")
    display(symbols_frame(type_map, label).head(50))

COIN: 566 symbols

            symbol
0           0GUSDT
1   1000000BOBUSDT
2   1000000MOGUSDT
3     1000BONKUSDC
4     1000BONKUSDT
5      1000CATUSDT
6   1000CHEEMSUSDT
7    1000FLOKIUSDT
8     1000LUNCUSDT
9     1000PEPEUSDC
10    1000PEPEUSDT
11    1000RATSUSDT
12    1000SATSUSDT
13    1000SHIBUSDC
14    1000SHIBUSDT
15     1000XECUSDT
16       1INCHUSDT
17  1MBABYDOGEUSDT
18          2ZUSDT
19           4USDT
20        AAVEUSDC
21        AAVEUSDT
22         ACEUSDT
23         ACHUSDT
24         ACTUSDT
25         ACUUSDT
26         ACXUSDT
27         ADAUSDC
28         ADAUSDT
29       AERGOUSDT
30        AEROUSDT
31        AEVOUSDT
32        AGLDUSDT
33         AGTUSDT
34         AIAUSDT
35    AIGENSYNUSDT
36         AINUSDT
37        AIOTUSDT
38         AIOUSDT
39       AIXBTUSDT
40         AKEUSDT
41         AKTUSDT
42        ALCHUSDT
43        ALGOUSDT
44       ALICEUSDT
45        ALLOUSDT
46      ALPINEUSDT
47         ALTUSDT
48       ANIMEUSDT
49        ANKRUSDT

EQUITY: 48 symbols

       symbol
0    AAPLUSDT
1     AMDUSDT
2    AMZNUSDT
3     ARMUSDT
4    AVGOUSDT
5    BABAUSDT
6      BEUSDT
7    BRKBUSDT
8    CBRSUSDT
9    COHRUSDT
10   COINUSDT
11   CRCLUSDT
12   CRWVUSDT
13   CSCOUSDT
14    DISUSDT
15   DRAMUSDT
16    EWJUSDT
17    EWYUSDT
18   FLNCUSDT
19  GOOGLUSDT
20     HDUSDT
21   HOODUSDT
22   INTCUSDT
23    JPMUSDT
24   LITEUSDT
25   METAUSDT
26   MRVLUSDT
27   MSFTUSDT
28   MSTRUSDT
29     MUUSDT
30   NBISUSDT
31   NVDAUSDT
32   ORCLUSDT
33   PAYPUSDT
34   PLTRUSDT
35   QCOMUSDT
36    QQQUSDT
37   RKLBUSDT
38   SNDKUSDT
39   SOXLUSDT
40    SPYUSDT
41   TSLAUSDT
42    TSMUSDT
43   UBERUSDT
44   USARUSDT
45      VUSDT
46    WDCUSDT
47    WMTUSDT

PREMARKET: 3 symbols

       symbol
0  OPENAIUSDT
1    QNTXUSDT
2    SPCXUSDT

COMMODITY: 8 symbols

       symbol
0      BZUSDT
1      CLUSDT
2  COPPERUSDT
3  NATGASUSDT
4     XAGUSDT
5     XAUUSDT
6     XPDUSDT
7     XPTUSDT

INDEX: 2 symbols

       symbol
0     ALLUSDT
1  BTCDOMUSDT

UNKNOWN: 0 symbols

Empty DataFrame
Columns: [symbol]
Index: []

## 4. underlyingSubType: Official Sector Tag To Symbols

In [6]:
subtype_summary = pd.DataFrame(
    [
        {
            "underlyingSubType": label,
            "symbol_count": len(symbols),
            "sample_symbols": symbols[:20],
        }
        for label, symbols in subtype_map.items()
    ]
).sort_values(["symbol_count", "underlyingSubType"], ascending=[False, True])

display(subtype_summary.reset_index(drop=True))

,underlyingSubType,symbol_count,sample_symbols
0,DeFi,117,"[1000LUNCUSDT, 1INCHUSDT, AAVEUSDT, ACXUSDT, A..."
1,Alpha,71,"[4USDT, ACUUSDT, AIAUSDT, AIGENSYNUSDT, AIOUSD..."
2,Infrastructure,59,"[2ZUSDT, AERGOUSDT, ALTUSDT, API3USDT, ARKMUSD..."
3,TradFi,59,"[AAPLUSDT, AMDUSDT, AMZNUSDT, ARMUSDT, AVGOUSD..."
4,AI,58,"[ACTUSDT, AGTUSDT, AINUSDT, AIOTUSDT, AIXBTUSD..."
5,Layer-1,53,"[0GUSDT, ADAUSDT, ALGOUSDT, APTUSDT, ARKUSDT, ..."
6,Meme,47,"[1000000BOBUSDT, 1000000MOGUSDT, 1000BONKUSDT,..."
7,USDC,37,"[1000BONKUSDC, 1000PEPEUSDC, 1000SHIBUSDC, AAV..."
8,Gaming,26,"[ACEUSDT, AGLDUSDT, BEAMXUSDT, BIGTIMEUSDT, CA..."
9,Layer-2,21,"[ARBUSDT, AUSDT, AZTECUSDT, BTRUSDT, CELRUSDT,..."
10,PoW,16,"[BSVUSDT, BTCUSDT, CFXUSDT, CKBUSDT, DASHUSDT,..."
11,UNKNOWN,16,"[ALPINEUSDT, ASRUSDT, AVAUSDT, BIOUSDT, BTCUSD..."
12,Metaverse,13,"[ALICEUSDT, AXSUSDT, DUSDT, EDUUSDT, HIGHUSDT,..."
13,Storage,10,"[ARUSDT, FILUSDT, HOTUSDT, RAREUSDT, RIFUSDT, ..."
14,NFT,9,"[ANIMEUSDT, APEUSDT, BLURUSDT, CHZUSDT, EPICUS..."
15,Payment,7,"[1000XECUSDT, ACHUSDT, BCHUSDT, COTIUSDT, HUMA..."
16,RWA,4,"[CFGUSDT, MANTRAUSDT, PAXGUSDT, XAUTUSDT]"
17,Chinese,3,"[币安人生USDT, 我踏马来了USDT, 龙虾USDT]"
18,Pre-IPO,3,"[OPENAIUSDT, QNTXUSDT, SPCXUSDT]"
19,Index,2,"[ALLUSDT, BTCDOMUSDT]"
20,Cross Pair,1,[ETHBTC]
21,ETF,1,[EWJUSDT]

In [7]:
for label in ["AI", "Layer-1", "Alpha", "Pre-IPO", "TradFi", "DeFi", "Meme", "UNKNOWN"]:
    symbols = subtype_map.get(label, [])
    print(f"{label}: {len(symbols)} symbols")
    display(symbols_frame(subtype_map, label).head(50))

AI: 58 symbols

          symbol
0        ACTUSDT
1        AGTUSDT
2        AINUSDT
3       AIOTUSDT
4      AIXBTUSDT
5        AKTUSDT
6       ALCHUSDT
7       ALLOUSDT
8        ARCUSDT
9        ATHUSDT
10     AVAAIUSDT
11       AWEUSDT
12      CGPTUSDT
13       CHRUSDT
14   CLANKERUSDT
15    COOKIEUSDT
16         CUSDT
17       FETUSDT
18       FHEUSDT
19     FLOCKUSDT
20      FLUXUSDT
21      GOATUSDT
22     GRASSUSDT
23  GRIFFAINUSDT
24       GRTUSDT
25      HOLOUSDT
26      IDOLUSDT
27        IOUSDT
28        IPUSDT
29      KITEUSDT
30        LAUSDT
31       LPTUSDT
32      MIRAUSDT
33       NFPUSDT
34       NILUSDT
35       NMRUSDT
36      OPENUSDT
37       PHAUSDT
38    PROMPTUSDT
39    RECALLUSDT
40       RLCUSDT
41    SAHARAUSDT
42      SENTUSDT
43     SHELLUSDT
44     SKYAIUSDT
45    SWARMSUSDT
46       SXTUSDT
47       TAGUSDT
48       TAOUSDT
49        TAUSDT

Layer-1: 53 symbols

       symbol
0      0GUSDT
1     ADAUSDT
2    ALGOUSDT
3     APTUSDT
4     ARKUSDT
5    ASTRUSDT
6    ATOMUSDT
7    AVAXUSDT
8      BBUSDT
9    BERAUSDT
10    BNBUSDT
11     CCUSDT
12   CELOUSDT
13    DOTUSDT
14   DUSKUSDT
15   EGLDUSDT
16    ETHUSDT
17   FLOWUSDT
18   HBARUSDT
19   HIVEUSDT
20    ICPUSDT
21    ICXUSDT
22   INITUSDT
23   IOSTUSDT
24    KASUSDT
25    KSMUSDT
26  LUNA2USDT
27   MINAUSDT
28   MOVEUSDT
29   MOVRUSDT
30   NEARUSDT
31    NEOUSDT
32    ONGUSDT
33  PARTIUSDT
34  PLUMEUSDT
35   QTUMUSDT
36   ROSEUSDT
37   SAGAUSDT
38   SCRTUSDT
39    SCRUSDT
40    SEIUSDT
41    SOLUSDT
42   STRKUSDT
43    SUIUSDT
44      SUSDT
45    TONUSDT
46    TRXUSDT
47    VETUSDT
48    VICUSDT
49   VTHOUSDT

Alpha: 71 symbols

            symbol
0            4USDT
1          ACUUSDT
2          AIAUSDT
3     AIGENSYNUSDT
4          AIOUSDT
5          AKEUSDT
6          APRUSDT
7         ARIAUSDT
8           ATUSDT
9        BASEDUSDT
10         BASUSDT
11        BEATUSDT
12        BILLUSDT
13        BIRBUSDT
14       BLESSUSDT
15       BLUAIUSDT
16         BSBUSDT
17       BULLAUSDT
18        CARVUSDT
19     CLANKERUSDT
20         CLOUSDT
21        COAIUSDT
22     COLLECTUSDT
23         CYSUSDT
24        DOODUSDT
25        ELSAUSDT
26         ESPUSDT
27       FIGHTUSDT
28       FOLKSUSDT
29      GENIUSUSDT
30         GUAUSDT
31        GWEIUSDT
32        HANAUSDT
33          INUSDT
34         INXUSDT
35        IRYSUSDT
36         JCTUSDT
37  JELLYJELLYUSDT
38        KGENUSDT
39         LABUSDT
40         LYNUSDT
41       MAGMAUSDT
42       NIGHTUSDT
43          ONUSDT
44         OPGUSDT
45      PHAROSUSDT
46    PIEVERSEUSDT
47       POWERUSDT
48         PRLUSDT
49         PTBUSDT

Pre-IPO: 3 symbols

       symbol
0  OPENAIUSDT
1    QNTXUSDT
2    SPCXUSDT

TradFi: 59 symbols

        symbol
0     AAPLUSDT
1      AMDUSDT
2     AMZNUSDT
3      ARMUSDT
4     AVGOUSDT
5     BABAUSDT
6       BEUSDT
7     BRKBUSDT
8       BZUSDT
9     CBRSUSDT
10      CLUSDT
11    COHRUSDT
12    COINUSDT
13  COPPERUSDT
14    CRCLUSDT
15    CRWVUSDT
16    CSCOUSDT
17     DISUSDT
18    DRAMUSDT
19     EWJUSDT
20     EWYUSDT
21    FLNCUSDT
22   GOOGLUSDT
23      HDUSDT
24    HOODUSDT
25    INTCUSDT
26     JPMUSDT
27    LITEUSDT
28    METAUSDT
29    MRVLUSDT
30    MSFTUSDT
31    MSTRUSDT
32      MUUSDT
33  NATGASUSDT
34    NBISUSDT
35    NVDAUSDT
36  OPENAIUSDT
37    ORCLUSDT
38    PAYPUSDT
39    PLTRUSDT
40    QCOMUSDT
41    QNTXUSDT
42     QQQUSDT
43    RKLBUSDT
44    SNDKUSDT
45    SOXLUSDT
46    SPCXUSDT
47     SPYUSDT
48    TSLAUSDT
49     TSMUSDT

DeFi: 117 symbols

          symbol
0   1000LUNCUSDT
1      1INCHUSDT
2       AAVEUSDT
3        ACXUSDT
4       AEROUSDT
5       AEVOUSDT
6       ANKRUSDT
7      ASTERUSDT
8    AUCTIONUSDT
9       AVNTUSDT
10        B2USDT
11      BABYUSDT
12    BANANAUSDT
13      BANDUSDT
14      BARDUSDT
15       BELUSDT
16       BNTUSDT
17        BRUSDT
18       C98USDT
19      CAKEUSDT
20     CETUSUSDT
21      CHIPUSDT
22      COMPUSDT
23       COWUSDT
24       CRVUSDT
25       CVXUSDT
26      DEEPUSDT
27      DEXEUSDT
28     DODOXUSDT
29      DOLOUSDT
30     DRIFTUSDT
31      DYDXUSDT
32      EDENUSDT
33      EDGEUSDT
34       ENAUSDT
35       ERAUSDT
36     ETHFIUSDT
37      EVAAUSDT
38     FLUIDUSDT
39     FOLKSUSDT
40      FRAXUSDT
41         FUSDT
42       GMXUSDT
43    HAEDALUSDT
44      HEMIUSDT
45       HFTUSDT
46      HOMEUSDT
47     HYPERUSDT
48      HYPEUSDT
49       INJUSDT

Meme: 47 symbols

             symbol
0    1000000BOBUSDT
1    1000000MOGUSDT
2      1000BONKUSDT
3       1000CATUSDT
4    1000CHEEMSUSDT
5     1000FLOKIUSDT
6      1000PEPEUSDT
7      1000RATSUSDT
8      1000SATSUSDT
9      1000SHIBUSDT
10   1MBABYDOGEUSDT
11    BANANAS31USDT
12         BANKUSDT
13          BANUSDT
14         BOMEUSDT
15        BRETTUSDT
16  BROCCOLI714USDT
17  BROCCOLIF3BUSDT
18            BUSDT
19     CHILLGUYUSDT
20         DOGEUSDT
21         DOGSUSDT
22     FARTCOINUSDT
23       GIGGLEUSDT
24         KOMAUSDT
25      MELANIAUSDT
26         MEMEUSDT
27          MEWUSDT
28      MOODENGUSDT
29      MUBARAKUSDT
30            MUSDT
31        NEIROUSDT
32         NEWTUSDT
33         ORDIUSDT
34        PENGUUSDT
35       PEOPLEUSDT
36       PIPPINUSDT
37         PNUTUSDT
38       POPCATUSDT
39         PUMPUSDT
40          SPXUSDT
41        TOSHIUSDT
42        TRUMPUSDT
43          TSTUSDT
44          TUTUSDT
45      USELESSUSDT
46          WIFUSDT

UNKNOWN: 16 symbols

        symbol
0   ALPINEUSDT
1      ASRUSDT
2      AVAUSDT
3      BIOUSDT
4      BTCUSD1
5      COSUSDT
6      CTRUSDT
7      EULUSDT
8       FFUSDT
9     ICNTUSDT
10      OGUSDT
11  RAYSOLUSDT
12  SANTOSUSDT
13   TOWNSUSDT
14    USDCUSDT
15     ZKCUSDT

In [12]:
symbols_frame(subtype_map, 'Alpha')['symbol'].to_list()

['4USDT',
 'ACUUSDT',
 'AIAUSDT',
 'AIGENSYNUSDT',
 'AIOUSDT',
 'AKEUSDT',
 'APRUSDT',
 'ARIAUSDT',
 'ATUSDT',
 'BASEDUSDT',
 'BASUSDT',
 'BEATUSDT',
 'BILLUSDT',
 'BIRBUSDT',
 'BLESSUSDT',
 'BLUAIUSDT',
 'BSBUSDT',
 'BULLAUSDT',
 'CARVUSDT',
 'CLANKERUSDT',
 'CLOUSDT',
 'COAIUSDT',
 'COLLECTUSDT',
 'CYSUSDT',
 'DOODUSDT',
 'ELSAUSDT',
 'ESPUSDT',
 'FIGHTUSDT',
 'FOLKSUSDT',
 'GENIUSUSDT',
 'GUAUSDT',
 'GWEIUSDT',
 'HANAUSDT',
 'INUSDT',
 'INXUSDT',
 'IRYSUSDT',
 'JCTUSDT',
 'JELLYJELLYUSDT',
 'KGENUSDT',
 'LABUSDT',
 'LYNUSDT',
 'MAGMAUSDT',
 'NIGHTUSDT',
 'ONUSDT',
 'OPGUSDT',
 'PHAROSUSDT',
 'PIEVERSEUSDT',
 'POWERUSDT',
 'PRLUSDT',
 'PTBUSDT',
 'QUSDT',
 'RAVEUSDT',
 'RIVERUSDT',
 'ROBOUSDT',
 'SAPIENUSDT',
 'SIRENUSDT',
 'SKRUSDT',
 'SPACEUSDT',
 'SPORTFUNUSDT',
 'STABLEUSDT',
 'STARUSDT',
 'TRADOORUSDT',
 'TRIAUSDT',
 'TRUTHUSDT',
 'UAIUSDT',
 'UBUSDT',
 'USUSDT',
 'WETUSDT',
 'XNYUSDT',
 'XPINUSDT',
 'ZKPUSDT']

## 5. Use The Dictionaries Directly

In [7]:
ai_symbols = subtype_map.get("AI", [])
layer1_symbols = subtype_map.get("Layer-1", [])
pre_ipo_symbols = subtype_map.get("Pre-IPO", [])
coin_symbols = type_map.get("COIN", [])

print("AI symbols:", ai_symbols[:30])
print("Layer-1 symbols:", layer1_symbols[:30])
print("Pre-IPO symbols:", pre_ipo_symbols[:30])
print("COIN symbols:", coin_symbols[:30])

selected_symbols = sorted(set(ai_symbols) | set(layer1_symbols) | set(pre_ipo_symbols))
print("Combined selected symbols:", len(selected_symbols))
print(selected_symbols[:50])

AI symbols: ['ACTUSDT', 'AGTUSDT', 'AINUSDT', 'AIOTUSDT', 'AIXBTUSDT', 'AKTUSDT', 'ALCHUSDT', 'ALLOUSDT', 'ARCUSDT', 'ATHUSDT', 'AVAAIUSDT', 'AWEUSDT', 'CGPTUSDT', 'CHRUSDT', 'CLANKERUSDT', 'COOKIEUSDT', 'CUSDT', 'FETUSDT', 'FHEUSDT', 'FLOCKUSDT', 'FLUXUSDT', 'GOATUSDT', 'GRASSUSDT', 'GRIFFAINUSDT', 'GRTUSDT', 'HOLOUSDT', 'IDOLUSDT', 'IOUSDT', 'IPUSDT', 'KITEUSDT']
Layer-1 symbols: ['0GUSDT', 'ADAUSDT', 'ALGOUSDT', 'APTUSDT', 'ARKUSDT', 'ASTRUSDT', 'ATOMUSDT', 'AVAXUSDT', 'BBUSDT', 'BERAUSDT', 'BNBUSDT', 'CCUSDT', 'CELOUSDT', 'DOTUSDT', 'DUSKUSDT', 'EGLDUSDT', 'ETHUSDT', 'FLOWUSDT', 'HBARUSDT', 'HIVEUSDT', 'ICPUSDT', 'ICXUSDT', 'INITUSDT', 'IOSTUSDT', 'KASUSDT', 'KSMUSDT', 'LUNA2USDT', 'MINAUSDT', 'MOVEUSDT', 'MOVRUSDT']
Pre-IPO symbols: ['OPENAIUSDT', 'QNTXUSDT', 'SPCXUSDT']
COIN symbols: ['0GUSDT', '1000000BOBUSDT', '1000000MOGUSDT', '1000BONKUSDC', '1000BONKUSDT', '1000CATUSDT', '1000CHEEMSUSDT', '1000FLOKIUSDT', '1000LUNCUSDT', '1000PEPEUSDC', '1000PEPEUSDT', '1000RATSUSDT', '1000SATSUSDT', '1000SHIBUSDC', '1000SHIBUSDT', '1000XECUSDT', '1INCHUSDT', '1MBABYDOGEUSDT', '2ZUSDT', '4USDT', 'AAVEUSDC', 'AAVEUSDT', 'ACEUSDT', 'ACHUSDT', 'ACTUSDT', 'ACUUSDT', 'ACXUSDT', 'ADAUSDC', 'ADAUSDT', 'AERGOUSDT']
Combined selected symbols: 114
['0GUSDT', 'ACTUSDT', 'ADAUSDT', 'AGTUSDT', 'AINUSDT', 'AIOTUSDT', 'AIXBTUSDT', 'AKTUSDT', 'ALCHUSDT', 'ALGOUSDT', 'ALLOUSDT', 'APTUSDT', 'ARCUSDT', 'ARKUSDT', 'ASTRUSDT', 'ATHUSDT', 'ATOMUSDT', 'AVAAIUSDT', 'AVAXUSDT', 'AWEUSDT', 'BBUSDT', 'BERAUSDT', 'BNBUSDT', 'CCUSDT', 'CELOUSDT', 'CGPTUSDT', 'CHRUSDT', 'CLANKERUSDT', 'COOKIEUSDT', 'CUSDT', 'DOTUSDT', 'DUSKUSDT', 'EGLDUSDT', 'ETHUSDT', 'FETUSDT', 'FHEUSDT', 'FLOCKUSDT', 'FLOWUSDT', 'FLUXUSDT', 'GOATUSDT', 'GRASSUSDT', 'GRIFFAINUSDT', 'GRTUSDT', 'HBARUSDT', 'HIVEUSDT', 'HOLOUSDT', 'ICPUSDT', 'ICXUSDT', 'IDOLUSDT', 'INITUSDT']

## Optional Filters

Use these variants when you need a narrower universe:

```python
# USDT-quoted contracts only
maps = get_um_futures_classification_maps(quote_assets=["USDT"])

# Crypto perpetual contracts only, excluding TRADIFI_PERPETUAL
maps = get_um_futures_classification_maps(contract_types=("PERPETUAL",))
```